/*
 * Equipment Registry Api
 *
 * Equipment Registry management for hospital system
 *
 * API version: 1.0.0
 * Contact: your_email@stuba.sk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package equiptrack

import (
	"github.com/gin-gonic/gin"
)

type EquipmentRegistryAPI interface {


    // CreateEquipment Post /api/equipment
    // Creates new equipment entry 
     CreateEquipment(c *gin.Context)

    // DeleteEquipment Delete /api/equipment/:equipmentId
    // Permanently deletes equipment record 
     DeleteEquipment(c *gin.Context)

    // GetEquipment Get /api/equipment/:equipmentId
    // Returns details of equipment 
     GetEquipment(c *gin.Context)

    // ListEquipment Get /api/equipment
    // Returns list of all equipment 
     ListEquipment(c *gin.Context)

    // UpdateEquipment Put /api/equipment/:equipmentId
    // Updates equipment entry 
     UpdateEquipment(c *gin.Context)

    // UpdateEquipmentStatus Patch /api/equipment/:equipmentId
    // Updates equipment status (e.g. decommission) 
     UpdateEquipmentStatus(c *gin.Context)

}