/*
 * Equipment Registry Api
 *
 * Equipment Registry management for hospital system
 *
 * API version: 1.0.0
 * Contact: your_email@stuba.sk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package equiptrack

type Equipment struct {

	Id string `json:"id"`

	Name string `json:"name"`

	Category string `json:"category"`

	Manufacturer string `json:"manufacturer"`

	SerialNumber string `json:"serialNumber"`

	PurchaseDate string `json:"purchaseDate"`

	WarrantyUntil string `json:"warrantyUntil,omitempty"`

	LifespanYears int32 `json:"lifespanYears,omitempty"`

	PurchasePrice float32 `json:"purchasePrice,omitempty"`

	Status EquipmentStatus `json:"status"`

	Note string `json:"note,omitempty"`

	Location Location `json:"location"`
}
