/*
 * Equipment Registry Api
 *
 * Equipment Registry management for hospital system
 *
 * API version: 1.0.0
 * Contact: your_email@stuba.sk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package equiptrack

type EquipmentStatus string

// List of EquipmentStatus
const (
	ACTIVE EquipmentStatus = "active"
	DAMAGED EquipmentStatus = "damaged"
	DECOMMISSIONED EquipmentStatus = "decommissioned"
)
