apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

configMapGenerator:
  - name: xle-equiptrack-webapi-mongodb-init
    files:
      - params/init-db.js
  - name: xle-equiptrack-webapi-config
    literals:
      - database=xle-equiptrack
      - collection=equipment
patches:
- path: patches/webapi.deployment.yaml
  target:
    group: apps
    version: v1
    kind: Deployment
    name: xle-equiptrack-webapi