kind: Service
apiVersion: v1
metadata:
  name: xle-equiptrack-webapi
spec:
  selector:
    pod: xle-equiptrack-webapi-label
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: webapi-port